import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Topnav from '../components/topnav'
import Topbar from '../components/topbar'
import Carousell from '../components/carousell'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Work in Progress</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Topbar/>
        <Topnav/>
      </header>
      
      <main>
        <Carousell/>
        {/* Work in Progress */}
      </main>
      <footer></footer>
    </div>
  )
}
