import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Topnav from '../components/topnav'
import Topbar from '../components/topbar'
import HeaderCarousel from '../components/headerCarousel'
import ShopGrid from '../components/shopGrid'
import Footer from '../components/footer'
import TopProductCarousel from '../components/topProductCarousel'

const data = [
  {
    text: 'Canvas Boards',
    imgSrc: '/shopGrid/canvas-board.jpg'
  },
  {
    text: 'Acrylic paint',
    imgSrc: '/shopGrid/acrylic-paint.jpg'
  },
  {
    text: 'Palette Knife',
    imgSrc: '/shopGrid/palette-knife.jpg'
  },
  {
    text: 'Acrylic Medium',
    imgSrc: '/shopGrid/acrylic-medium.jpg'
  },
  {
    text: 'Brush',
    imgSrc: '/shopGrid/brush.jpg'
  },
  {
    text: 'Oil Stick',
    imgSrc: '/shopGrid/oil-stick.jpg'
  },
  {
    text: 'Golden Fluid Acrylic',
    imgSrc: '/shopGrid/golden-fluid-acrylic.jpg'
  },
  {
    text: 'Encaustic Paint',
    imgSrc: '/shopGrid/encaustic-paint.jpg'
  },
  {
    text: 'Easel',
    imgSrc: '/shopGrid/easel.jpg'
  },
  {
    text: 'Oil Paint',
    imgSrc: '/shopGrid/oil-paint.jpg'
  },
  {
    text: 'Watercolor',
    imgSrc: '/shopGrid/watercolor.jpg'
  },
  {
    text: 'Oil Medium',
    imgSrc: '/shopGrid/oil-medium.jpg'
  }
]
export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Art & Supplies Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Topbar />
        <Topnav />
      </header>

      <main className={styles.main}>
        <HeaderCarousel />
        <ShopGrid data={data} />
        {/* <TopProductCarousel/> */}
      </main>
      <Footer/>
    </div>
  )
}
